# Generated by Django 3.2.21 on 2024-02-01 16:11

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api_gate', '0016_securemessage_shift_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transit',
            name='requested_by',
            field=models.CharField(default=settings.FONTUR_API_USER, max_length=15),
        ),
    ]